server:
  port: 8080

spring:
  application:
    name: demo222
  datasource:
    url: jdbc:mysql://localhost:3306/agricultural_ims?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 050825
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.demo222.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: AgriMgmtSys2026SecretKeyForJwtTokenGeneration!@#$%
  expiration: 86400000